const data = {
    products:[
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt1',
            category: 'Shirts',
            image: '/images/p2.png',
            price: 120,
            countInStock: 0,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
            description: 'sample product',
        },
        {
            _id: '2',
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt2',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'sample product',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt3',
            category: 'Shirts',
            image: '/images/p2.png',
            price: 120,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'sample product',
        },
    ],
};

export default data;